CREATE TABLE public."quality_assessments" (
metadata_uuid	uuid,
quality_id	bigint NOT NULL,
assessment_date	date,
version_when_assessed	date,
resources_when_assessed	character varying(3),
thumb_present	character varying(3),
map_included	character varying(3),
thumb_represent_dataset	character varying(3),
thumb_comments	text,
extent_dataset	character varying(3),
extent_comments	text,
meaningfulness_title_fr	character varying(3),
meaningfulness_title_en	character varying(3),
date_format_compliant_fr	character varying(3),
date_format_compliant_en	character varying(3),
scale_format_compliant_fr	character varying(3),
scale_format_compliant_en	character varying(3),
no_starting_with_fr 	character varying(3),
no_starting_with_en	character varying(3),
acronyms_defined_fr	character varying(3),
acronyms_defined_en	character varying(3),
no_org_name_fr	character varying(3),
no_org_name_en	character varying(3),
title_comments 	text,
meaningfulness_kw	character varying(3),
nb_keywords_compliant	character varying(3),
no_determinants	character varying(3),
nb_topics_compliant	character varying(3),
keywords_comments	text,
tbs_openess_fr	character varying(3),
tbs_openess_en	character varying(3),
meaningfulness_ab_fr	character varying(3),
meaningfulness_ab_en	character varying(3),
abstract_comments 	text,
supdoc_present_fr	character varying(3),
supdoc_present_en	character varying(3),
supportingdoc_comments	text,
working_links	character varying(3),
honest	character varying(3),
international	character varying(3),
web_service_available 	character varying(3),
view_this_map_functional	character varying(3),
accessibility_comments	text,
open_fomat_present	character varying(3),
open_webservice_present	character varying(3),
open_comments	text,
good_resources_name_translation	character varying(3),
good_resources_content_translation	character varying(3),
resource_comments_translation	text,
good_title_translation	character varying(3),
good_keywords_translation	character varying(3),
good_abstract_translation 	character varying(3),
mandatory_comments_translation	text,
good_legend_translation	character varying(3),
good_attributes_translation	character varying(3),
map_content_comments_translation	text,
fast_loading_time_fr	character varying(3),
fast_loading_time_en	character varying(3),
too_many_layers_slow_fr	character varying(3),
too_many_layers_slow_en	character varying(3),
relevant_at_scale_fr	character varying(3),
relevant_at_scale_en	character varying(3),
mapscaling_comments 	text,
symbols_distinct_fr	character varying(3),
symbols_distinct_en	character varying(3),
scale_adjusting_fr	character varying(3),
scale_adjusting_en	character varying(3),
proper_topo_principles_fr	character varying(3),
proper_topo_principles_en	character varying(3),
categories_related_to_topic_fr	character varying(3),
categories_related_to_topic_en	character varying(3),
appropriate_geometry_fr	character varying(3),
appropriate_geometry_en	character varying(3),
mapsymbology_comments	text,
legend_map_consistent_fr	character varying(3),
legend_map_consistent_en	character varying(3),
legend_viewable_fr	character varying(3),
legend_viewable_en	character varying(3),
appropriate_legend_fr	character varying(3),
appropriate_legend_en	character varying(3),
legend_no_acronyms_fr	character varying(3),
legend_no_acronyms_en	character varying(3),
description_clear_fr	character varying(3),
description_clear_en	character varying(3),
legend_comments	text,
attributes_present_fr	character varying(3),
attributes_present_en	character varying(3),
understandable_attributes_fr 	character varying(3),
understandable_attributes_en	character varying(3),
featureattandvalues_comments	text,
metadata_hnap_compliant	character varying(3),
hnap_comments 	text,
CONSTRAINT "quality_assessments_pkey" PRIMARY KEY (quality_id));

CREATE TABLE public."dictionnary"(
indicator_variable_code	character varying(50),
indicator_variable_fr	text,
indicator_variable_en	text,
indicator_code	character varying(50),
indicator_fr	character varying(50),
indicator_en	character varying(50),
sub_indicator_code	character varying(50),
sub_indicator_fr	character varying(50),
sub_indicator_en	character varying(50),

CONSTRAINT "dictionnary_pkey" PRIMARY KEY (indicator_variable_code));
)



